In [297]:
import numpy as np

In [389]:
input_layer=np.random.rand(3)
weights1=np.random.rand(5,3)*5
biases1=-np.random.rand(1,5)

In [390]:
y=np.array([[1,1]])

In [391]:
input_layer

array([0.74063866, 0.70259624, 0.277349  ])

In [392]:
weights1

array([[3.00939879, 0.99912509, 0.91893201],
       [2.66052836, 0.89849581, 3.24352813],
       [1.98086943, 2.23253007, 2.32733074],
       [4.94078124, 1.42145758, 4.25331565],
       [1.39472594, 3.88714672, 4.01381688]])

In [393]:
biases1

array([[-0.76337302, -0.89683856, -0.56768175, -0.90478   , -0.22272118]])

In [394]:
M=np.dot(weights1,input_layer)+biases

In [395]:
M

array([[2.52085109, 2.94703026, 3.36137707, 5.6419227 , 3.98758391]])

In [396]:
#forward propogation
def forward_prop(M):
    hiddenlayer=1/(1+np.exp(-M))
    return hiddenlayer

In [397]:
hiddenlayer=forward_prop(M)

In [398]:
hiddenlayer

array([[0.92559069, 0.95012294, 0.96647542, 0.99646649, 0.98179317]])

In [399]:
weights2=np.random.rand(5,2)
Biases2=np.random.rand(2)

In [400]:
weights2

array([[0.52750476, 0.33927886],
       [0.02511869, 0.71014196],
       [0.89659241, 0.58766732],
       [0.1693411 , 0.06384927],
       [0.38580153, 0.60792493]])

In [401]:
Biases2

array([0.35201615, 0.46255553])

In [402]:
#let's take output layer inputs as P
P=np.dot(hiddenlayer,weights2)

In [403]:
P

array([[1.92617391, 2.21720175]])

In [404]:
outputlayer_outputs=forward_prop(P)

In [405]:
outputlayer_outputs

array([[0.87282532, 0.90178363]])

In [406]:
mse=((outputlayer_outputs-y)**2).sum()/2*2
mse

0.025819852828049036

In [415]:
learning_rate=0.1
epochs=10000

In [416]:
#backpropogation
#I did it using only numpy
for epoch in  range(epochs) :
    outputlayer_error=outputlayer_outputs-y
    outputlayer_delta=outputlayer_error*outputlayer_outputs*(1-outputlayer_outputs)

    #weight update
    weights2_update=np.dot(hiddenlayer.T,outputlayer_delta)/2
    weights2=weights2-learning_rate*weights2_update

In [417]:
P=np.dot(hiddenlayer,weights2)
outputlayer_outputs=forward_prop(P)

In [419]:
mse=((outputlayer_outputs-y)**2).sum()/2*2
mse

0.00010539300126413979

#error is reduced from original 0.0258 to 0.000105